language: scala
scala:
    - 2.11.7
services:
    - mysql
before_install:
    - mysql -e "create database IF NOT EXISTS all4journey;" -uroot
    - sbt domain/flywayMigrate -Dflyway_password=""
jdk:
    - oraclejdk8
script: sbt test -Ddb_config="travis-db"

notifications:
    email:
        recipients:
            -rjkernick@gmail.com
            -andy.abreu@gmail.com
